



DROP TABLE PERSON;
CREATE TABLE PERSON (
      USERNAME VARCHAR(20) NOT NULL,
      PASSWORD VARCHAR(20),
      FIRST_NAME VARCHAR(40),
      MIDDLE_NAME VARCHAR(40),
      LAST_NAME VARCHAR(40),
      TITLE VARCHAR(10),
      SUFFIX VARCHAR(10),
      HOME_PHONE VARCHAR(20),
      WORK_PHONE VARCHAR(20),
      FAX VARCHAR(20),
      EMAIL VARCHAR(255),
      HOME_STREET1 VARCHAR(100),
      HOME_STREET2 VARCHAR(100),
      HOME_CITY VARCHAR(60),
      HOME_COUNTY VARCHAR(60),
      HOME_STATE VARCHAR(60),
      HOME_COUNTRY VARCHAR(60),
      HOME_POSTAL_CODE VARCHAR(60),
  PRIMARY KEY (USERNAME));

DROP TABLE PERSON_ATTRIBUTE;
CREATE TABLE PERSON_ATTRIBUTE (
      USERNAME VARCHAR(20) NOT NULL,
      NAME VARCHAR(40) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (USERNAME, NAME));

DROP TABLE PERSON_TYPE;
CREATE TABLE PERSON_TYPE (
      TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (TYPE_ID));

DROP TABLE PERSON_TYPE_ATTRIBUTE;
CREATE TABLE PERSON_TYPE_ATTRIBUTE (
      TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(40) NOT NULL,
  PRIMARY KEY (TYPE_ID, NAME));

DROP TABLE PERSON_PERSON_TYPE;
CREATE TABLE PERSON_PERSON_TYPE (
      USERNAME VARCHAR(20) NOT NULL,
      TYPE_ID VARCHAR(40) NOT NULL,
  PRIMARY KEY (USERNAME, TYPE_ID));

DROP TABLE SECURITY_GROUP;
CREATE TABLE SECURITY_GROUP (
      GROUP_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GROUP_ID));

DROP TABLE SECURITY_PERMISSION;
CREATE TABLE SECURITY_PERMISSION (
      PERMISSION_ID VARCHAR(60) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PERMISSION_ID));

DROP TABLE SECURITY_GROUP_PERMISSION;
CREATE TABLE SECURITY_GROUP_PERMISSION (
      GROUP_ID VARCHAR(20) NOT NULL,
      PERMISSION_ID VARCHAR(60) NOT NULL,
  PRIMARY KEY (GROUP_ID, PERMISSION_ID));

DROP TABLE PERSON_SECURITY_GROUP;
CREATE TABLE PERSON_SECURITY_GROUP (
      USERNAME VARCHAR(20) NOT NULL,
      GROUP_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (USERNAME, GROUP_ID));

DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (
      SKU VARCHAR(40) NOT NULL,
      SHORT_DESC VARCHAR(255),
      LONG_DESC TEXT,
      SMALL_IMAGE_URL VARCHAR(255),
      LARGE_IMAGE_URL VARCHAR(255),
      PROMO_IMAGE_URL VARCHAR(255),
      MORE_INFO_URL VARCHAR(255),
      TYPE_ID VARCHAR(20),
      UNIT_OF_MEASURE VARCHAR(10),
      PRODUCT_TYPE NUMERIC,
      WEIGHT NUMERIC,
  PRIMARY KEY (SKU));

DROP TABLE FIXED_ASSET;
CREATE TABLE FIXED_ASSET (
      FIXED_ASSET_ID VARCHAR(20) NOT NULL,
      COMPANY_UNIT_ID VARCHAR(40),
      OWNER_USERNAME VARCHAR(20),
      SALE_TRANS_ID VARCHAR(20),
      SALE_TRANS_LINE_ID VARCHAR(20),
      PURCHASE_TRANS_ID VARCHAR(20),
      PURCHASE_TRANS_LINE_ID VARCHAR(20),
      DESCRIPTION VARCHAR(255),
      TYPE_ID VARCHAR(20),
      SERIAL_NUMBER VARCHAR(80),
      MAKE VARCHAR(40),
      MODEL VARCHAR(40),
      YEAR VARCHAR(10),
      STATUS VARCHAR(20),
      NOTES TEXT,
  PRIMARY KEY (FIXED_ASSET_ID));

DROP TABLE FIXED_ASSET_ATTRIBUTE;
CREATE TABLE FIXED_ASSET_ATTRIBUTE (
      FIXED_ASSET_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(40) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (FIXED_ASSET_ID, NAME));

