




DROP TABLE GEO;
CREATE TABLE GEO (
      GEO_ID VARCHAR(20) NOT NULL,
      GEO_TYPE_ID VARCHAR(20),
      NAME VARCHAR(60),
      GEO_CODE VARCHAR(60),
      ABBREVIATION VARCHAR(60),
  PRIMARY KEY (GEO_ID));

DROP TABLE GEO_TYPE;
CREATE TABLE GEO_TYPE (
      GEO_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GEO_TYPE_ID));

DROP TABLE GEO_ASSOC;
CREATE TABLE GEO_ASSOC (
      GEO_ID VARCHAR(20) NOT NULL,
      GEO_ID_TO VARCHAR(20) NOT NULL,
      GEO_ASSOC_TYPE_ID VARCHAR(20),
  PRIMARY KEY (GEO_ID, GEO_ID_TO));

DROP TABLE GEO_ASSOC_TYPE;
CREATE TABLE GEO_ASSOC_TYPE (
      GEO_ASSOC_TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GEO_ASSOC_TYPE_ID));

DROP TABLE PERIOD_TYPE;
CREATE TABLE PERIOD_TYPE (
      PERIOD_TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PERIOD_TYPE_ID));

DROP TABLE STANDARD_TIME_PERIOD;
CREATE TABLE STANDARD_TIME_PERIOD (
      STANDARD_TIME_PERIOD_ID VARCHAR(20) NOT NULL,
      PERIOD_TYPE_ID VARCHAR(20),
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
  PRIMARY KEY (STANDARD_TIME_PERIOD_ID));

DROP TABLE STATUS;
CREATE TABLE STATUS (
      STATUS_ID VARCHAR(20) NOT NULL,
      STATUS_TYPE_ID VARCHAR(20),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (STATUS_ID));

DROP TABLE STATUS_TYPE;
CREATE TABLE STATUS_TYPE (
      STATUS_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (STATUS_TYPE_ID));

DROP TABLE UOM;
CREATE TABLE UOM (
      UOM_ID VARCHAR(20) NOT NULL,
      UOM_TYPE_ID VARCHAR(20),
      ABBREVIATION VARCHAR(60),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (UOM_ID));

DROP TABLE UOM_TYPE;
CREATE TABLE UOM_TYPE (
      UOM_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (UOM_TYPE_ID));

DROP TABLE UOM_CONVERSION;
CREATE TABLE UOM_CONVERSION (
      UOM_ID VARCHAR(20) NOT NULL,
      UOM_ID_TO VARCHAR(20) NOT NULL,
      CONVERSION_FACTOR NUMERIC(18,6),
  PRIMARY KEY (UOM_ID, UOM_ID_TO));

DROP TABLE PARTY;
CREATE TABLE PARTY (
      PARTY_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (PARTY_ID));

DROP TABLE PARTY_CLASSIFICATION;
CREATE TABLE PARTY_CLASSIFICATION (
      PARTY_ID VARCHAR(20) NOT NULL,
      PARTY_TYPE_ID VARCHAR(20) NOT NULL,
      PARTY_CLASSIFICATION_TYPE_ID VARCHAR(20),
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
  PRIMARY KEY (PARTY_ID, PARTY_TYPE_ID));

DROP TABLE PARTY_CLASSIFICATION_TYPE;
CREATE TABLE PARTY_CLASSIFICATION_TYPE (
      PARTY_CLASSIFICATION_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PARTY_CLASSIFICATION_TYPE_ID));

DROP TABLE PARTY_TYPE;
CREATE TABLE PARTY_TYPE (
      PARTY_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PARTY_TYPE_ID));

DROP TABLE PARTY_ATTRIBUTE;
CREATE TABLE PARTY_ATTRIBUTE (
      PARTY_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (PARTY_ID, NAME));

DROP TABLE PARTY_TYPE_ATTR;
CREATE TABLE PARTY_TYPE_ATTR (
      PARTY_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (PARTY_TYPE_ID, NAME));

DROP TABLE PARTY_ROLE;
CREATE TABLE PARTY_ROLE (
      PARTY_ID VARCHAR(20) NOT NULL,
      ROLE_TYPE_ID VARCHAR(20) NOT NULL,
      PARTY_ROLE_ID VARCHAR(20),
  PRIMARY KEY (PARTY_ID, ROLE_TYPE_ID));

DROP TABLE ROLE_TYPE;
CREATE TABLE ROLE_TYPE (
      ROLE_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (ROLE_TYPE_ID));

DROP TABLE ROLE_TYPE_ATTR;
CREATE TABLE ROLE_TYPE_ATTR (
      ROLE_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (ROLE_TYPE_ID, NAME));

DROP TABLE PRODUCT;
CREATE TABLE PRODUCT (
      PRODUCT_ID VARCHAR(20) NOT NULL,
      PRIMARY_PRODUCT_CATEGORY_ID VARCHAR(20),
      MANUFACTURER_PARTY_ID VARCHAR(20),
      UOM_ID VARCHAR(20),
      QUANTITY_INCLUDED NUMERIC(18,6),
      INTRODUCTION_DATE DATETIME,
      SALES_DISCONTINUATION_DATE DATETIME,
      SUPPORT_DISCONTINUATION_DATE DATETIME,
      NAME VARCHAR(60),
      COMMENT VARCHAR(255),
      DESCRIPTION VARCHAR(255),
      LONG_DESCRIPTION TEXT,
      SMALL_IMAGE_URL VARCHAR(255),
      LARGE_IMAGE_URL VARCHAR(255),
      DEFAULT_PRICE NUMERIC(18,2),
  PRIMARY KEY (PRODUCT_ID));

DROP TABLE PRODUCT_CLASS;
CREATE TABLE PRODUCT_CLASS (
      PRODUCT_ID VARCHAR(20) NOT NULL,
      PRODUCT_TYPE_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
  PRIMARY KEY (PRODUCT_ID, PRODUCT_TYPE_ID));

DROP TABLE PRODUCT_TYPE;
CREATE TABLE PRODUCT_TYPE (
      PRODUCT_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_TYPE_ID));

DROP TABLE PRODUCT_ATTRIBUTE;
CREATE TABLE PRODUCT_ATTRIBUTE (
      PRODUCT_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (PRODUCT_ID, NAME));

DROP TABLE PRODUCT_TYPE_ATTR;
CREATE TABLE PRODUCT_TYPE_ATTR (
      PRODUCT_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (PRODUCT_TYPE_ID, NAME));

DROP TABLE GOOD_IDENTIFICATION;
CREATE TABLE GOOD_IDENTIFICATION (
      GOOD_IDENTIFICATION_TYPE_ID VARCHAR(20) NOT NULL,
      PRODUCT_ID VARCHAR(20) NOT NULL,
      ID_VALUE VARCHAR(60),
  PRIMARY KEY (GOOD_IDENTIFICATION_TYPE_ID, PRODUCT_ID));

DROP TABLE GOOD_IDENTIFICATION_TYPE;
CREATE TABLE GOOD_IDENTIFICATION_TYPE (
      GOOD_IDENTIFICATION_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GOOD_IDENTIFICATION_TYPE_ID));

DROP TABLE PRODUCT_ASSOC;
CREATE TABLE PRODUCT_ASSOC (
      PRODUCT_ID VARCHAR(20) NOT NULL,
      PRODUCT_ID_TO VARCHAR(20) NOT NULL,
      PRODUCT_ASSOC_TYPE_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      REASON VARCHAR(255),
      QUANTITY NUMERIC(18,6),
      INSTRUCTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_ID, PRODUCT_ID_TO, PRODUCT_ASSOC_TYPE_ID));

DROP TABLE PRODUCT_ASSOC_TYPE;
CREATE TABLE PRODUCT_ASSOC_TYPE (
      PRODUCT_ASSOC_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_ASSOC_TYPE_ID));

DROP TABLE PRODUCT_DATA_OBJECT;
CREATE TABLE PRODUCT_DATA_OBJECT (
      DATA_OBJECT_ID VARCHAR(20) NOT NULL,
      PRODUCT_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (DATA_OBJECT_ID, PRODUCT_ID));

DROP TABLE PRODUCT_CATEGORY;
CREATE TABLE PRODUCT_CATEGORY (
      PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_CATEGORY_ID));

DROP TABLE PRODUCT_CATEGORY_CLASS;
CREATE TABLE PRODUCT_CATEGORY_CLASS (
      PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
      PRODUCT_CATEGORY_TYPE_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
  PRIMARY KEY (PRODUCT_CATEGORY_ID, PRODUCT_CATEGORY_TYPE_ID));

DROP TABLE PRODUCT_CATEGORY_TYPE;
CREATE TABLE PRODUCT_CATEGORY_TYPE (
      PRODUCT_CATEGORY_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_CATEGORY_TYPE_ID));

DROP TABLE PRODUCT_CATEGORY_ATTRIBUTE;
CREATE TABLE PRODUCT_CATEGORY_ATTRIBUTE (
      PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (PRODUCT_CATEGORY_ID, NAME));

DROP TABLE PRODUCT_CATEGORY_TYPE_ATTR;
CREATE TABLE PRODUCT_CATEGORY_TYPE_ATTR (
      PRODUCT_CATEGORY_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (PRODUCT_CATEGORY_TYPE_ID, NAME));

DROP TABLE PRODUCT_CATEGORY_MEMBER;
CREATE TABLE PRODUCT_CATEGORY_MEMBER (
      PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
      PRODUCT_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      PRIMARY_FLAG CHAR(1),
      COMMENT VARCHAR(255),
  PRIMARY KEY (PRODUCT_CATEGORY_ID, PRODUCT_ID));

DROP TABLE PRODUCT_CATEGORY_ROLLUP;
CREATE TABLE PRODUCT_CATEGORY_ROLLUP (
      PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
      PARENT_PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (PRODUCT_CATEGORY_ID, PARENT_PRODUCT_CATEGORY_ID));

DROP TABLE PRODUCT_FEATURE;
CREATE TABLE PRODUCT_FEATURE (
      PRODUCT_FEATURE_ID VARCHAR(20) NOT NULL,
      PRODUCT_FEATURE_TYPE_ID VARCHAR(20),
      PRODUCT_FEATURE_CATEGORY_ID VARCHAR(20),
      DESCRIPTION VARCHAR(255),
      UOM_ID VARCHAR(20),
      NUMBER_SPECIFIED NUMERIC(18,0),
  PRIMARY KEY (PRODUCT_FEATURE_ID));

DROP TABLE PRODUCT_FEATURE_TYPE;
CREATE TABLE PRODUCT_FEATURE_TYPE (
      PRODUCT_FEATURE_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_FEATURE_TYPE_ID));

DROP TABLE PRODUCT_FEATURE_CATEGORY;
CREATE TABLE PRODUCT_FEATURE_CATEGORY (
      PRODUCT_FEATURE_CATEGORY_ID VARCHAR(20) NOT NULL,
      PARENT_CATEGORY_ID VARCHAR(20),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_FEATURE_CATEGORY_ID));

DROP TABLE PRODUCT_FEATURE_APPL;
CREATE TABLE PRODUCT_FEATURE_APPL (
      PRODUCT_ID VARCHAR(20) NOT NULL,
      PRODUCT_FEATURE_ID VARCHAR(20) NOT NULL,
      PRODUCT_FEATURE_APPL_TYPE_ID VARCHAR(20),
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
  PRIMARY KEY (PRODUCT_ID, PRODUCT_FEATURE_ID));

DROP TABLE PRODUCT_FEATURE_APPL_TYPE;
CREATE TABLE PRODUCT_FEATURE_APPL_TYPE (
      PRODUCT_FEATURE_APPL_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_FEATURE_APPL_TYPE_ID));

DROP TABLE PRODUCT_FEATURE_IACTN;
CREATE TABLE PRODUCT_FEATURE_IACTN (
      PRODUCT_FEATURE_ID VARCHAR(20) NOT NULL,
      PRODUCT_FEATURE_ID_TO VARCHAR(20) NOT NULL,
      PRODUCT_FEATURE_IACTN_TYPE_ID VARCHAR(20),
      PRODUCT_ID VARCHAR(20),
  PRIMARY KEY (PRODUCT_FEATURE_ID, PRODUCT_FEATURE_ID_TO));

DROP TABLE PRODUCT_FEATURE_IACTN_TYPE;
CREATE TABLE PRODUCT_FEATURE_IACTN_TYPE (
      PRODUCT_FEATURE_IACTN_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRODUCT_FEATURE_IACTN_TYPE_ID));

DROP TABLE FEATURE_DATA_OBJECT;
CREATE TABLE FEATURE_DATA_OBJECT (
      DATA_OBJECT_ID VARCHAR(20) NOT NULL,
      PRODUCT_FEATURE_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (DATA_OBJECT_ID, PRODUCT_FEATURE_ID));

DROP TABLE COST_COMPONENT;
CREATE TABLE COST_COMPONENT (
      COST_COMPONENT_ID VARCHAR(20) NOT NULL,
      COST_COMPONENT_TYPE_ID VARCHAR(20),
      PRODUCT_ID VARCHAR(20),
      PRODUCT_FEATURE_ID VARCHAR(20),
      PARTY_ID VARCHAR(20),
      GEO_ID VARCHAR(20),
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      COST NUMERIC(18,2),
  PRIMARY KEY (COST_COMPONENT_ID));

DROP TABLE COST_COMPONENT_TYPE;
CREATE TABLE COST_COMPONENT_TYPE (
      COST_COMPONENT_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (COST_COMPONENT_TYPE_ID));

DROP TABLE COST_COMPONENT_ATTRIBUTE;
CREATE TABLE COST_COMPONENT_ATTRIBUTE (
      COST_COMPONENT_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (COST_COMPONENT_ID, NAME));

DROP TABLE COST_COMPONENT_TYPE_ATTR;
CREATE TABLE COST_COMPONENT_TYPE_ATTR (
      COST_COMPONENT_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (COST_COMPONENT_TYPE_ID, NAME));

DROP TABLE PRICE_COMPONENT;
CREATE TABLE PRICE_COMPONENT (
      PRICE_COMPONENT_ID VARCHAR(20) NOT NULL,
      PRICE_COMPONENT_TYPE_ID VARCHAR(20),
      PARTY_ID VARCHAR(20),
      PARTY_TYPE_ID VARCHAR(20),
      PRODUCT_ID VARCHAR(20),
      PRODUCT_FEATURE_ID VARCHAR(20),
      PRODUCT_CATEGORY_ID VARCHAR(20),
      AGREEMENT_ID VARCHAR(20),
      AGREEMENT_ITEM_SEQ_ID VARCHAR(20),
      UOM_ID VARCHAR(20),
      GEO_ID VARCHAR(20),
      SALE_TYPE_ID VARCHAR(20),
      ORDER_VALUE_BREAK_ID VARCHAR(20),
      QUANTITY_BREAK_ID VARCHAR(20),
      UTILIZATION_UOM_ID VARCHAR(20),
      UTILIZATION_QUANTITY NUMERIC(18,6),
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      PRICE NUMERIC(18,2),
      PERCENT NUMERIC(18,6),
      COMMENT VARCHAR(255),
  PRIMARY KEY (PRICE_COMPONENT_ID));

DROP TABLE PRICE_COMPONENT_TYPE;
CREATE TABLE PRICE_COMPONENT_TYPE (
      PRICE_COMPONENT_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PRICE_COMPONENT_TYPE_ID));

DROP TABLE PRICE_COMPONENT_ATTRIBUTE;
CREATE TABLE PRICE_COMPONENT_ATTRIBUTE (
      PRICE_COMPONENT_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (PRICE_COMPONENT_ID, NAME));

DROP TABLE PRICE_COMPONENT_TYPE_ATTR;
CREATE TABLE PRICE_COMPONENT_TYPE_ATTR (
      PRICE_COMPONENT_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (PRICE_COMPONENT_TYPE_ID, NAME));

DROP TABLE QUANTITY_BREAK;
CREATE TABLE QUANTITY_BREAK (
      QUANTITY_BREAK_ID VARCHAR(20) NOT NULL,
      FROM_QUANTITY NUMERIC(18,6),
      THRU_QUANTITY NUMERIC(18,6),
  PRIMARY KEY (QUANTITY_BREAK_ID));

DROP TABLE ORDER_VALUE_BREAK;
CREATE TABLE ORDER_VALUE_BREAK (
      ORDER_VALUE_BREAK_ID VARCHAR(20) NOT NULL,
      FROM_AMOUNT NUMERIC(18,2),
      THRU_AMOUNT NUMERIC(18,2),
  PRIMARY KEY (ORDER_VALUE_BREAK_ID));

DROP TABLE SALE_TYPE;
CREATE TABLE SALE_TYPE (
      SALE_TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (SALE_TYPE_ID));

DROP TABLE INVENTORY_ITEM;
CREATE TABLE INVENTORY_ITEM (
      INVENTORY_ITEM_ID VARCHAR(20) NOT NULL,
      INVENTORY_ITEM_TYPE_ID VARCHAR(20),
      PRODUCT_ID VARCHAR(20),
      PARTY_ID VARCHAR(20),
      STATUS_TYPE_ID VARCHAR(20),
      FACILITY_ID VARCHAR(20),
      CONTAINER_ID VARCHAR(20),
      LOT_ID VARCHAR(20),
      UOM_ID VARCHAR(20),
      QUANTITY_ON_HAND NUMERIC(18,6),
      SERIAL_NUMBER VARCHAR(255),
  PRIMARY KEY (INVENTORY_ITEM_ID));

DROP TABLE INVENTORY_ITEM_TYPE;
CREATE TABLE INVENTORY_ITEM_TYPE (
      INVENTORY_ITEM_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (INVENTORY_ITEM_TYPE_ID));

DROP TABLE INVENTORY_ITEM_ATTRIBUTE;
CREATE TABLE INVENTORY_ITEM_ATTRIBUTE (
      INVENTORY_ITEM_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (INVENTORY_ITEM_ID, NAME));

DROP TABLE INVENTORY_ITEM_TYPE_ATTR;
CREATE TABLE INVENTORY_ITEM_TYPE_ATTR (
      INVENTORY_ITEM_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (INVENTORY_ITEM_TYPE_ID, NAME));

DROP TABLE PHYSICAL_INVENTORY;
CREATE TABLE PHYSICAL_INVENTORY (
      PHYSICAL_INVENTORY_ID VARCHAR(20) NOT NULL,
      DATE DATETIME,
      PARTY_ID VARCHAR(20),
      COMMENT VARCHAR(255),
  PRIMARY KEY (PHYSICAL_INVENTORY_ID));

DROP TABLE INVENTORY_ITEM_VARIANCE;
CREATE TABLE INVENTORY_ITEM_VARIANCE (
      INVENTORY_ITEM_ID VARCHAR(20) NOT NULL,
      PHYSICAL_INVENTORY_ID DATETIME NOT NULL,
      VARIANCE_REASON_ID VARCHAR(20),
      QUANTITY NUMERIC(18,6),
      COMMENT VARCHAR(255),
  PRIMARY KEY (INVENTORY_ITEM_ID, PHYSICAL_INVENTORY_ID));

DROP TABLE VARIANCE_REASON;
CREATE TABLE VARIANCE_REASON (
      VARIANCE_REASON_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (VARIANCE_REASON_ID));

DROP TABLE ITEM_VARIANCE_ACCTG_TRANS;
CREATE TABLE ITEM_VARIANCE_ACCTG_TRANS (
      ACCTG_TRANS_ID VARCHAR(20) NOT NULL,
      INVENTORY_ITEM_ID VARCHAR(20),
      PHYSICAL_INVENTORY_ID DATETIME,
  PRIMARY KEY (ACCTG_TRANS_ID));

DROP TABLE LOT;
CREATE TABLE LOT (
      LOT_ID VARCHAR(20) NOT NULL,
      CREATION_DATE DATETIME,
      QUANTITY NUMERIC(18,6),
      EXPIRATION_DATE DATETIME,
  PRIMARY KEY (LOT_ID));

DROP TABLE CONTAINER;
CREATE TABLE CONTAINER (
      CONTAINER_ID VARCHAR(20) NOT NULL,
      CONTAINER_TYPE_ID VARCHAR(20),
      FACILITY_ID VARCHAR(20),
  PRIMARY KEY (CONTAINER_ID));

DROP TABLE CONTAINER_TYPE;
CREATE TABLE CONTAINER_TYPE (
      CONTAINER_TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (CONTAINER_TYPE_ID));

DROP TABLE FACILITY;
CREATE TABLE FACILITY (
      FACILITY_ID VARCHAR(20) NOT NULL,
      FACILITY_TYPE_ID VARCHAR(20),
      FACILITY_NAME VARCHAR(60),
      SQUARE_FOOTAGE NUMERIC(18,0),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (FACILITY_ID));

DROP TABLE FACILITY_TYPE;
CREATE TABLE FACILITY_TYPE (
      FACILITY_TYPE_ID VARCHAR(20) NOT NULL,
      PARENT_TYPE_ID VARCHAR(20),
      HAS_TABLE CHAR(1),
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (FACILITY_TYPE_ID));

DROP TABLE FACILITY_ATTRIBUTE;
CREATE TABLE FACILITY_ATTRIBUTE (
      FACILITY_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
      VALUE VARCHAR(255),
  PRIMARY KEY (FACILITY_ID, NAME));

DROP TABLE FACILITY_TYPE_ATTR;
CREATE TABLE FACILITY_TYPE_ATTR (
      FACILITY_TYPE_ID VARCHAR(20) NOT NULL,
      NAME VARCHAR(60) NOT NULL,
  PRIMARY KEY (FACILITY_TYPE_ID, NAME));

DROP TABLE FACILITY_CONTACT_MECHANISM;
CREATE TABLE FACILITY_CONTACT_MECHANISM (
      FACILITY_ID VARCHAR(20) NOT NULL,
      CONTACT_MECHANISM_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (FACILITY_ID, CONTACT_MECHANISM_ID));

DROP TABLE PARTY_FACILITY;
CREATE TABLE PARTY_FACILITY (
      PARTY_ID VARCHAR(20) NOT NULL,
      FACILITY_ID VARCHAR(20) NOT NULL,
      FACILITY_ROLE_TYPE_ID VARCHAR(20),
  PRIMARY KEY (PARTY_ID, FACILITY_ID));

DROP TABLE FACILITY_ROLE_TYPE;
CREATE TABLE FACILITY_ROLE_TYPE (
      FACILITY_ROLE_TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (FACILITY_ROLE_TYPE_ID));

DROP TABLE REORDER_GUIDELINE;
CREATE TABLE REORDER_GUIDELINE (
      REORDER_GUIDELINE_ID VARCHAR(20) NOT NULL,
      PRODUCT_ID VARCHAR(20),
      PARTY_ID VARCHAR(20),
      ROLE_TYPE_ID VARCHAR(20),
      FACILITY_ID VARCHAR(20),
      GEO_ID VARCHAR(20),
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      REORDER_QUANTITY NUMERIC(18,6),
      REORDER_LEVEL NUMERIC(18,6),
  PRIMARY KEY (REORDER_GUIDELINE_ID));

DROP TABLE SUPPLIER_PRODUCT;
CREATE TABLE SUPPLIER_PRODUCT (
      PRODUCT_ID VARCHAR(20) NOT NULL,
      PARTY_ID VARCHAR(20) NOT NULL,
      AVAILABLE_FROM_DATE DATETIME,
      AVAILABLE_THRU_DATE DATETIME,
      SUPPLIER_PREF_ORDER_ID VARCHAR(20),
      SUPPLIER_RATING_TYPE_ID VARCHAR(20),
      STANDARD_LEAD_TIME DATETIME,
      COMMENT VARCHAR(255),
  PRIMARY KEY (PRODUCT_ID, PARTY_ID));

DROP TABLE SUPPLIER_RATING_TYPE;
CREATE TABLE SUPPLIER_RATING_TYPE (
      SUPPLIER_RATING_TYPE_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (SUPPLIER_RATING_TYPE_ID));

DROP TABLE SUPPLIER_PREF_ORDER;
CREATE TABLE SUPPLIER_PREF_ORDER (
      SUPPLIER_PREF_ORDER_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (SUPPLIER_PREF_ORDER_ID));

DROP TABLE MARKET_INTEREST;
CREATE TABLE MARKET_INTEREST (
      PRODUCT_CATEGORY_ID VARCHAR(20) NOT NULL,
      PARTY_TYPE_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
  PRIMARY KEY (PRODUCT_CATEGORY_ID, PARTY_TYPE_ID));

DROP TABLE USER_LOGIN;
CREATE TABLE USER_LOGIN (
      USER_LOGIN_ID VARCHAR(20) NOT NULL,
      PARTY_ID VARCHAR(20),
      CONTACT_MECHANISM_ID VARCHAR(20),
      CURRENT_USER_ID VARCHAR(20),
      CURRENT_PASSWORD VARCHAR(60),
  PRIMARY KEY (USER_LOGIN_ID));

DROP TABLE LOGIN_ACCOUNT_HISTORY;
CREATE TABLE LOGIN_ACCOUNT_HISTORY (
      USER_LOGIN_ID VARCHAR(20) NOT NULL,
      USER_LOGIN_SEQ_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      PARTY_ID VARCHAR(20),
      USER_ID VARCHAR(20),
      PASSWORD VARCHAR(60),
  PRIMARY KEY (USER_LOGIN_ID, USER_LOGIN_SEQ_ID));

DROP TABLE SECURITY_GROUP;
CREATE TABLE SECURITY_GROUP (
      GROUP_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GROUP_ID));

DROP TABLE SECURITY_PERMISSION;
CREATE TABLE SECURITY_PERMISSION (
      PERMISSION_ID VARCHAR(60) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PERMISSION_ID));

DROP TABLE SECURITY_GROUP_PERMISSION;
CREATE TABLE SECURITY_GROUP_PERMISSION (
      GROUP_ID VARCHAR(20) NOT NULL,
      PERMISSION_ID VARCHAR(60) NOT NULL,
  PRIMARY KEY (GROUP_ID, PERMISSION_ID));

DROP TABLE USER_LOGIN_SECURITY_GROUP;
CREATE TABLE USER_LOGIN_SECURITY_GROUP (
      USER_LOGIN_ID VARCHAR(20) NOT NULL,
      GROUP_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (USER_LOGIN_ID, GROUP_ID));

