

DROP TABLE USER_LOGIN;
CREATE TABLE USER_LOGIN (
      USER_LOGIN_ID VARCHAR(20) NOT NULL,
      PARTY_ID VARCHAR(20),
      CONTACT_MECHANISM_ID VARCHAR(20),
      CURRENT_USER_ID VARCHAR(20),
      CURRENT_PASSWORD VARCHAR(60),
  PRIMARY KEY (USER_LOGIN_ID));

DROP TABLE LOGIN_ACCOUNT_HISTORY;
CREATE TABLE LOGIN_ACCOUNT_HISTORY (
      USER_LOGIN_ID VARCHAR(20) NOT NULL,
      USER_LOGIN_SEQ_ID VARCHAR(20) NOT NULL,
      FROM_DATE DATETIME,
      THRU_DATE DATETIME,
      PARTY_ID VARCHAR(20),
      USER_ID VARCHAR(20),
      PASSWORD VARCHAR(60),
  PRIMARY KEY (USER_LOGIN_ID, USER_LOGIN_SEQ_ID));

DROP TABLE SECURITY_GROUP;
CREATE TABLE SECURITY_GROUP (
      GROUP_ID VARCHAR(20) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (GROUP_ID));

DROP TABLE SECURITY_PERMISSION;
CREATE TABLE SECURITY_PERMISSION (
      PERMISSION_ID VARCHAR(60) NOT NULL,
      DESCRIPTION VARCHAR(255),
  PRIMARY KEY (PERMISSION_ID));

DROP TABLE SECURITY_GROUP_PERMISSION;
CREATE TABLE SECURITY_GROUP_PERMISSION (
      GROUP_ID VARCHAR(20) NOT NULL,
      PERMISSION_ID VARCHAR(60) NOT NULL,
  PRIMARY KEY (GROUP_ID, PERMISSION_ID));

DROP TABLE USER_LOGIN_SECURITY_GROUP;
CREATE TABLE USER_LOGIN_SECURITY_GROUP (
      USER_LOGIN_ID VARCHAR(20) NOT NULL,
      GROUP_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (USER_LOGIN_ID, GROUP_ID));

