
-- GEO Boundary Type
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CITY', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('STATE', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('POSTAL_CODE', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COUNTRY', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COUNTY', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COUNTY_CITY', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PROVINCE', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REGION', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_TERRITORY', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SERVICE_TERRITORY', 'N', '');
INSERT INTO GEO_TYPE (GEO_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TERRITORY', 'N', '');

-- Unit Of Measure Type
INSERT INTO UOM_TYPE (UOM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CURRENCY_MEASURE', 'N', '');
INSERT INTO UOM_TYPE (UOM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TIME_FREQUENCY_MEASURE', 'N', '');

-- Data Object Type
INSERT INTO DATA_OBJECT_TYPE (DATA_OBJECT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ELECTRONIC_TEXT', 'Y', '');
INSERT INTO DATA_OBJECT_TYPE (DATA_OBJECT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('IMAGE_OBJECT', 'Y', '');
INSERT INTO DATA_OBJECT_TYPE (DATA_OBJECT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_OBJECT', 'Y', '');

-- Content Type
INSERT INTO CONTENT_TYPE (CONTENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ARTICLE', 'N', '');
INSERT INTO CONTENT_TYPE (CONTENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_INFO', 'N', '');
INSERT INTO CONTENT_TYPE (CONTENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COMPANY_INFO', 'N', '');
INSERT INTO CONTENT_TYPE (CONTENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ADVERTISEMENT', 'N', '');

-- Subscription Type
INSERT INTO SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('NEWSGROUP_SUBSCRIPTION', 'N', '');
INSERT INTO SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_SUBSCRIPTION', 'N', '');
INSERT INTO SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_INFORMATION_SUBSCRIPTION', 'N', '');

-- Contact Mechanism Type
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ELECTRONIC_ADDRESS', 'N', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORDER_CONTACT_MECH', 'Y', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORDER_ITEM_CONTACT_MECH', 'Y', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('POSTAL_ADDRESS', 'Y', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TELECOMMUNICATIONS_NUMBER', 'Y', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FACILITY_CONTACT_MECH', 'Y', '');
-- --
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EMAIL_ADDRESS', 'N', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('IP_ADDRESS', 'N', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DOMAIN_NAME', 'N', '');
INSERT INTO CONTACT_MECH_TYPE (CONTACT_MECH_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WEB_ADDRESS', 'N', '');

-- Contact Mechanism Purpose Type
INSERT INTO CONTACT_MECH_PURPOSE_TYPE (CONTACT_MECH_PURPOSE_TYPE_ID, DESCRIPTION) VALUES ('SHIPPING_LOCATION', '');
INSERT INTO CONTACT_MECH_PURPOSE_TYPE (CONTACT_MECH_PURPOSE_TYPE_ID, DESCRIPTION) VALUES ('BILLING_LOCATION', '');


-- Communication Event Type
INSERT INTO COMMUNICATION_EVENT_TYPE (COMMUNICATION_EVENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EMAIL_COMMUNICATION', 'N', '');
INSERT INTO COMMUNICATION_EVENT_TYPE (COMMUNICATION_EVENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FACE_TO_FACE_COMMUNICATION', 'N', '');
INSERT INTO COMMUNICATION_EVENT_TYPE (COMMUNICATION_EVENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FAX_COMMUNICATION', 'N', '');
INSERT INTO COMMUNICATION_EVENT_TYPE (COMMUNICATION_EVENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('LETTER_CORRESPONDENCE', 'N', '');
INSERT INTO COMMUNICATION_EVENT_TYPE (COMMUNICATION_EVENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PHONE_COMMUNICATION', 'N', '');
INSERT INTO COMMUNICATION_EVENT_TYPE (COMMUNICATION_EVENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WEB_SITE_COMMUNICATION', 'N', '');

-- Communication Event Purpose Type
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ACTIVITY_REQUEST', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CONFERENCE', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CUSTOMER_SERVICE_CALL', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INQUIRY', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MEETING', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_FOLLOW_UP', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SEMINAR', 'N', '');
INSERT INTO COMMUNICATION_EVENT_PRP_TYP (COMMUNICATION_EVENT_PRP_TYP_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUPPORT_CALL', 'N', '');

-- Party Type
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PERSON', 'Y', '');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORGANIZATION', 'N', '');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('LEGAL_ORGANIZATION', 'N', 'ORGANIZATION');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INFORMAL_ORGANIZATION', 'N', 'ORGANIZATION');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FAMILY', 'N', 'INFORMAL_ORGANIZATION');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CORPORATION', 'N', 'LEGAL_ORGANIZATION');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('GOVERNMENT_AGENCY', 'N', 'LEGAL_ORGANIZATION');
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TEAM', 'N', 'INFORMAL_ORGANIZATION');
-- --
INSERT INTO PARTY_TYPE (PARTY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AUTOMATED_AGENT', 'N', '');

-- Party Type Attr
INSERT INTO PARTY_TYPE_ATTR (PARTY_TYPE_ID, NAME) VALUES ('LEGAL_ORGANIZATION', 'FEDERAL_TAX_ID_NUM');
INSERT INTO PARTY_TYPE_ATTR (PARTY_TYPE_ID, NAME) VALUES ('ORGANIZATION', 'NAME');

-- Party Role Type
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PROSPECT', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SHAREHOLDER', 'N', '');

INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PERSON_ROLE', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EMPLOYEE', 'N', 'PERSON_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CONTRACTOR', 'N', 'PERSON_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CONTACT', 'N', 'PERSON_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FAMILY_MEMBER', 'N', 'PERSON_ROLE');

INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CUSTOMER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('END_USER_CUSTOMER', 'N', 'CUSTOMER');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SHIP_TO_CUSTOMER', 'N', 'CUSTOMER');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BILL_TO_CUSTOMER', 'N', 'CUSTOMER');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PLACING_CUSTOMER', 'N', 'CUSTOMER');

INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORGANIZATION_ROLE', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PARTNER', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUPPLIER', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COMPETITOR', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('HOUSEHOLD', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ASSOCIATION', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REGULATORY_AGENCY', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INTERNAL_ORGANIZATION', 'Y', 'ORGANIZATION_ROLE');

INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISTRIBUTION_CHANNEL', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISTRIBUTOR', 'N', 'DISTRIBUTION_CHANNEL');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AGENT', 'N', 'DISTRIBUTION_CHANNEL');

INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORGANIZATION_UNIT', 'N', 'ORGANIZATION_ROLE');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_ORGANIZATION_UNIT', 'N', 'ORGANIZATION_UNIT');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PARENT_ORGANIZATION', 'N', 'ORGANIZATION_UNIT');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DEPARTMENT', 'N', 'ORGANIZATION_UNIT');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DIVISION', 'N', 'ORGANIZATION_UNIT');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUBSIDIARY', 'N', 'ORGANIZATION_UNIT');

INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CARRIER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MANAGER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_INTERNAL_ORGANIZATION', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('UNION', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORKER', 'N', '');
-- --
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AUTOMATED_AGENT_ROLE', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CONSUMER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('HOSTING_SERVER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ISP', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REFERRER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUBSCRIBER', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('VISITOR', 'N', '');
INSERT INTO ROLE_TYPE (ROLE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WEB_MASTER', 'N', '');

-- Party Role Type Type
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AGREEMENT_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BILLING_ACCOUNT_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BUDGET_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CASE_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COMMUNICATION_EVENT_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FINCANCIAL_ACCOUNT_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INVOICE_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ITEM_ISSUANCE_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORDER_ITEM_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORDER_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('QUOTE_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REQUEST_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REQUIREMENT_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SHIPMENT_RECEIPT_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TIMESHEET_ROLE_TYPE', 'N', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('VALID_CONTACT_MECH_ROLE_TYPE', 'Y', '');
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFFORT_ROLE_TYPE', 'N', '');
-- --
-- INSERT INTO PARTY_ROLE_TYPE_TYPE (TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WEB_CONTENT_ROLE_TYPE', 'N', '');

-- Party Classification Type
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EEOC_CLASSIFICATION', 'N', '');
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MINORITY_CLASSIFICATION', 'N', '');
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INCOME_CLASSIFICATION', 'N', '');
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INDUSTRY_CLASSIFICATION', 'N', '');
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORGANIZATION_CLASSIFICATION', 'N', '');
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PERSON_CLASSIFICATION', 'N', '');
INSERT INTO PARTY_CLASSIFICATION_TYPE (PARTY_CLASSIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SIZE_CLASSIFICATION', 'N', '');

-- Party Relationship Type
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISTRIBUTION_CHANNEL_RELATIONSHIP', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EMPLOYMENT', 'Y', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORGANIZATION_CONTRACT_RELATIONSHIP', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORGANIZATION_ROLLUP', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PARTNERSHIP', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUPPLIER_RELATIONSHIP', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CUSTOMER_RELATIONSHIP', 'N', '');
-- --
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('HOST_SERVER_VISITOR', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('VISITOR_ISP', 'N', '');
INSERT INTO PARTY_RELATIONSHIP_TYPE (PARTY_RELATIONSHIP_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WEB_MASTER_ASSIGNMENT', 'N', '');


-- Product Type
INSERT INTO PRODUCT_TYPE (PRODUCT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SERVICE', 'N', 'NONE');
INSERT INTO PRODUCT_TYPE (PRODUCT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('GOOD', 'N', 'NONE');
INSERT INTO PRODUCT_TYPE (PRODUCT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('RAW_MATERIAL', 'N', 'GOOD');
INSERT INTO PRODUCT_TYPE (PRODUCT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUBASSEMBLY', 'N', 'GOOD');
INSERT INTO PRODUCT_TYPE (PRODUCT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FINISHED_GOOD', 'N', 'GOOD');

-- Product Feature Type
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BILLING_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BRAND', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COLOR', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('HARDWARE_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_QUALITY', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SIZE', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SOFTWARE_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_TYPE (PRODUCT_FEATURE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DIMENSION', 'N', '');

-- Product Feature Interaction Type
INSERT INTO PRODUCT_FEATURE_IACTN_TYPE (PRODUCT_FEATURE_IACTN_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FEATURE_IACTN_DEPENDENCY', 'N', '');
INSERT INTO PRODUCT_FEATURE_IACTN_TYPE (PRODUCT_FEATURE_IACTN_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FEATURE_IACTN_INCOMPATIBILITY', 'N', '');

-- Product Feature Applicability Type
INSERT INTO PRODUCT_FEATURE_APPL_TYPE (PRODUCT_FEATURE_APPL_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OPTIONAL_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_APPL_TYPE (PRODUCT_FEATURE_APPL_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REQUIRED_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_APPL_TYPE (PRODUCT_FEATURE_APPL_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SELECTABLE_FEATURE', 'N', '');
INSERT INTO PRODUCT_FEATURE_APPL_TYPE (PRODUCT_FEATURE_APPL_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('STANDARD_FEATURE', 'N', '');

-- Product Category Type
INSERT INTO PRODUCT_CATEGORY_TYPE (PRODUCT_CATEGORY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_INDUSTRY_CATEGORIZATION', 'N', '');
INSERT INTO PRODUCT_CATEGORY_TYPE (PRODUCT_CATEGORY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_MATERIALS_CATEGORIZATION', 'N', '');
INSERT INTO PRODUCT_CATEGORY_TYPE (PRODUCT_CATEGORY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_USAGE_CATEGORIZATION', 'N', '');

-- Price Component Type
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BASE_PRICE', 'N', '');
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MANUFACTURER_SUGGESTED_PRICE', 'N', '');
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ONE_TIME_CHARGE', 'N', '');
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('RECURRING_CHARGE', 'Y', '');
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISCOUNT_COMPONENT', 'N', '');
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SURCHARGE_COMPONENT', 'N', '');
INSERT INTO PRICE_COMPONENT_TYPE (PRICE_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('UTILIZATION_SURCHARGE', 'Y', '');

-- Estimated Product Cost Type
INSERT INTO COST_COMPONENT_TYPE (COST_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ESTIMATED_LABOR_COST', 'N', '');
INSERT INTO COST_COMPONENT_TYPE (COST_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ESTIMATED_MATERIALS_COST', 'N', '');
INSERT INTO COST_COMPONENT_TYPE (COST_COMPONENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ESTIMATED_OTHER_COSTS', 'N', '');

-- Good Identification Type
INSERT INTO GOOD_IDENTIFICATION_TYPE (GOOD_IDENTIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ISBN', 'N', '');
INSERT INTO GOOD_IDENTIFICATION_TYPE (GOOD_IDENTIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MANUFACTURER_ID_NO', 'N', '');
INSERT INTO GOOD_IDENTIFICATION_TYPE (GOOD_IDENTIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_ID', 'N', '');
INSERT INTO GOOD_IDENTIFICATION_TYPE (GOOD_IDENTIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SKU', 'N', '');
INSERT INTO GOOD_IDENTIFICATION_TYPE (GOOD_IDENTIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('UPCA', 'N', '');
INSERT INTO GOOD_IDENTIFICATION_TYPE (GOOD_IDENTIFICATION_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('UPCE', 'N', '');

-- Product Association Type
INSERT INTO PRODUCT_ASSOC_TYPE (PRODUCT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_COMPLEMENT', 'N', '');
INSERT INTO PRODUCT_ASSOC_TYPE (PRODUCT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_INCOMPATABILITY', 'N', '');
INSERT INTO PRODUCT_ASSOC_TYPE (PRODUCT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_OBSOLESCENCE', 'N', '');
INSERT INTO PRODUCT_ASSOC_TYPE (PRODUCT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MARKETING_PACKAGE', 'N', '');
INSERT INTO PRODUCT_ASSOC_TYPE (PRODUCT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_COMPONENT', 'N', '');
INSERT INTO PRODUCT_ASSOC_TYPE (PRODUCT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_SUBSTITUTE', 'N', '');

-- Inventory Item Type
INSERT INTO INVENTORY_ITEM_TYPE (INVENTORY_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SERIALIZED_INVENTORY_ITEM', 'N', '');
INSERT INTO INVENTORY_ITEM_TYPE (INVENTORY_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('NON_SERIALIZED_INVENTORY_ITEM', 'N', '');

-- Facility Type
INSERT INTO FACILITY_TYPE (FACILITY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OFFICE', 'N', '');
INSERT INTO FACILITY_TYPE (FACILITY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ROOM', 'N', '');
INSERT INTO FACILITY_TYPE (FACILITY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PLANT', 'N', '');
INSERT INTO FACILITY_TYPE (FACILITY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FLOOR', 'N', '');
INSERT INTO FACILITY_TYPE (FACILITY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BUILDING', 'N', '');
INSERT INTO FACILITY_TYPE (FACILITY_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WAREHOUSE', 'N', '');


-- Quote Type
INSERT INTO QUOTE_TYPE (QUOTE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_QUOTE', 'N', '');
INSERT INTO QUOTE_TYPE (QUOTE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_QUOTE', 'N', '');
INSERT INTO QUOTE_TYPE (QUOTE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PROPOSAL', 'N', '');

-- Order Type
INSERT INTO ORDER_TYPE (ORDER_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_ORDER', 'N', '');
INSERT INTO ORDER_TYPE (ORDER_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_ORDER', 'N', '');
INSERT INTO ORDER_TYPE (ORDER_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_ORDER', 'N', '');

-- Order Item Type
INSERT INTO ORDER_ITEM_TYPE (ORDER_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_ORDER_ITEM', 'N', '');
INSERT INTO ORDER_ITEM_TYPE (ORDER_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_ORDER_ITEM', 'N', '');
INSERT INTO ORDER_ITEM_TYPE (ORDER_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_ORDER_ITEM', 'N', '');

-- Order Adjustment Type
INSERT INTO ORDER_ADJUSTMENT_TYPE (ORDER_ADJUSTMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISCOUNT_ADJUSTMENT', 'N', '');
INSERT INTO ORDER_ADJUSTMENT_TYPE (ORDER_ADJUSTMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FEE', 'N', '');
INSERT INTO ORDER_ADJUSTMENT_TYPE (ORDER_ADJUSTMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MISCELLANEOUS_CHARGE', 'N', '');
INSERT INTO ORDER_ADJUSTMENT_TYPE (ORDER_ADJUSTMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_TAX', 'N', '');
INSERT INTO ORDER_ADJUSTMENT_TYPE (ORDER_ADJUSTMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SHIPPING_AND_HANDLING_CHARGES', 'N', '');
INSERT INTO ORDER_ADJUSTMENT_TYPE (ORDER_ADJUSTMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SURCHARGE_ADJUSTMENT', 'N', '');

-- Status Type Type
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BUDGET_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CASE_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('COMMUNICATION_EVENT_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EMPLOYMENT_APPLICATION_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INVENTORY_ITEM_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INVOICE_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ORDER_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('POSITION_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REQUIREMENT_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SHIPMENT_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('UNEMPLOYMENT_CLAIM_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFF_ASSET_ASSIGN_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFFORT_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PARTY_ASSET_ASSIGNMENT_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PARTY_RELATIONSHIP_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SERVER_HIT_STATUS', 'N', '');
INSERT INTO STATUS_TYPE (STATUS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WEB_CONTENT_STATUS', 'N', '');

-- Customer Request Type
INSERT INTO CUST_REQUEST_TYPE (CUST_REQUEST_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID, DESCRIPTION) VALUES ('RFI', 'N', '', 'Request For Information');
INSERT INTO CUST_REQUEST_TYPE (CUST_REQUEST_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID, DESCRIPTION) VALUES ('RFP', 'N', '', 'Request For Proposal');
INSERT INTO CUST_REQUEST_TYPE (CUST_REQUEST_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID, DESCRIPTION) VALUES ('RFQ', 'N', '', 'Request For Quote');

-- Requirement Type
INSERT INTO REQUIREMENT_TYPE (REQUIREMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CUSTOMER_REQUIREMENT', 'N', '');
INSERT INTO REQUIREMENT_TYPE (REQUIREMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INTERNAL_REQUIREMENT', 'N', '');
INSERT INTO REQUIREMENT_TYPE (REQUIREMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_REQUIREMENT', 'Y', '');
INSERT INTO REQUIREMENT_TYPE (REQUIREMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_REQUIREMENT', 'Y', '');

-- Shipment Type
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CUSTOMER_RETURN', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CUSTOMER_SHIPMENT', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DROP_SHIPMENT', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INCOMING_SHIPMENT', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OUTGOING_SHIPMENT', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_RETURN', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_SHIPMENT', 'N', '');
INSERT INTO SHIPMENT_TYPE (SHIPMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TRANSFER', 'N', '');

-- Document Type
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SHIPPING_DOCUMENT', 'Y', '');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BILL_OF_LADING', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EXPORT_DOCUMENTATION', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('HAZARDOUS_MATERIALS_DOCUMENT', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MANIFEST', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_SHIPPING_DOCUMENT', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PACKAGING_SLIP', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PORT_CHARGES_DOCUMENT', 'N', 'SHIPPING_DOCUMENT');
INSERT INTO DOCUMENT_TYPE (DOCUMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TAX_AND_TARIFF_DOCUMENT', 'N', 'SHIPPING_DOCUMENT');

-- Work Effort Type
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PROGRAM', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PHASE', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PROJECT', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TASK', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ACTIVITY', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCTION_RUN', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('MAINTENANCE', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('RESEARCH', 'N', '');
INSERT INTO WORK_EFFORT_TYPE (WORK_EFFORT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_FLOW', 'N', '');

-- Work Effort Type Attr
INSERT INTO WORK_EFFORT_TYPE_ATTR (WORK_EFFORT_TYPE_ID, NAME) VALUES ('PRODUCTION_RUN', 'QUANTITY_TO_PRODUCE');
INSERT INTO WORK_EFFORT_TYPE_ATTR (WORK_EFFORT_TYPE_ID, NAME) VALUES ('PRODUCTION_RUN', 'QUANTITY_PRODUCED');
INSERT INTO WORK_EFFORT_TYPE_ATTR (WORK_EFFORT_TYPE_ID, NAME) VALUES ('PRODUCTION_RUN', 'QUANTITY_REJECTED');

-- Work Effort Association Type
INSERT INTO WORK_EFFORT_ASSOC_TYPE (WORK_EFFORT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFFORT_BREAKDOWN', 'N', '');
INSERT INTO WORK_EFFORT_ASSOC_TYPE (WORK_EFFORT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFFORT_DEPENDENCY', 'N', '');
INSERT INTO WORK_EFFORT_ASSOC_TYPE (WORK_EFFORT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFFORT_CONCURRENCY', 'N', 'WORK_EFFORT_DEPENDENCY');
INSERT INTO WORK_EFFORT_ASSOC_TYPE (WORK_EFFORT_ASSOC_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WORK_EFFORT_PRECEDENCY', 'N', 'WORK_EFFORT_DEPENDENCY');

-- Financial Account Type
INSERT INTO FIN_ACCOUNT_TYPE (FIN_ACCOUNT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('BANK_ACCOUNT', 'N', '');
INSERT INTO FIN_ACCOUNT_TYPE (FIN_ACCOUNT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INVESTMENT_ACCOUNT', 'N', '');

-- Financial Account Trans Type
INSERT INTO FIN_ACCOUNT_TRANS_TYPE (FIN_ACCOUNT_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DEPOSIT', 'N', '');
INSERT INTO FIN_ACCOUNT_TRANS_TYPE (FIN_ACCOUNT_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('WITHDRAWAL', 'Y', '');

-- Invoice Type
INSERT INTO INVOICE_TYPE (INVOICE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_INVOICE', 'N', '');
INSERT INTO INVOICE_TYPE (INVOICE_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_INVOICE', 'N', '');

-- Invoice Item Type
INSERT INTO INVOICE_ITEM_TYPE (INVOICE_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_INVOICE_ITEM', 'N', '');
INSERT INTO INVOICE_ITEM_TYPE (INVOICE_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_INVOICE_ITEM', 'N', '');

-- Payment Type
INSERT INTO PAYMENT_TYPE (PAYMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISBURSEMENT', 'N', '');
INSERT INTO PAYMENT_TYPE (PAYMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PAY_CHECK', 'Y', 'DISBURSEMENT');
INSERT INTO PAYMENT_TYPE (PAYMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('RECEIPT', 'Y', '');

-- Budget Type
INSERT INTO BUDGET_TYPE (BUDGET_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CAPITAL_BUDGET', 'N', '');
INSERT INTO BUDGET_TYPE (BUDGET_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OPERATING_BUDGET', 'N', '');

-- Budget Item Type
INSERT INTO BUDGET_ITEM_TYPE (BUDGET_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('REQUIREMENT_BUDGET_ALLOCATION', 'Y', '');

-- Fixed Asset Type
INSERT INTO FIXED_ASSET_TYPE (FIXED_ASSET_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EQUIPMENT', 'N', '');
INSERT INTO FIXED_ASSET_TYPE (FIXED_ASSET_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_FIXED_ASSET', 'N', '');
INSERT INTO FIXED_ASSET_TYPE (FIXED_ASSET_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PROPERTY', 'N', '');
INSERT INTO FIXED_ASSET_TYPE (FIXED_ASSET_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('VEHICLE', 'N', '');

-- Accounting Transaction Type
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INTERNAL_ACCTG_TRANS', 'Y', '');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AMORTIZATION', 'N', 'INTERNAL_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DEPRECIATION', 'Y', 'INTERNAL_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CAPITALIZATION', 'N', 'INTERNAL_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('ITEM_VARIANCE_ACCTG_TRANS', 'Y', 'INTERNAL_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_INTERNAL_ACCTG_TRANS', 'N', 'INTERNAL_ACCTG_TRANS');

INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EXTERNAL_ACCTG_TRANS', 'Y', '');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OBLIGATION_ACCTG_TRANS', 'N', 'EXTERNAL_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CREDIT_LINE', 'N', 'OBLIGATION_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CREDIT_MEMO', 'N', 'OBLIGATION_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('NOTE', 'N', 'OBLIGATION_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_OBLIGATION', 'N', 'OBLIGATION_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_ACCTG_TRANS', 'Y', 'OBLIGATION_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('TAX_DUE', 'N', 'OBLIGATION_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PAYMENT_ACCTG_TRANS', 'Y', 'EXTERNAL_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DISBURSEMENT_ACCTG_TRANS', 'N', 'PAYMENT_ACCTG_TRANS');
INSERT INTO ACCTG_TRANS_TYPE (ACCTG_TRANS_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('RECEIPT_ACCTG_TRANS', 'N', 'PAYMENT_ACCTG_TRANS');

-- Agreement Type
INSERT INTO AGREEMENT_TYPE (AGREEMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PRODUCT_AGREEMENT', 'N', '');
INSERT INTO AGREEMENT_TYPE (AGREEMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('PURCHASE_AGREEMENT', 'N', 'PRODUCT_AGREEMENT');
INSERT INTO AGREEMENT_TYPE (AGREEMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SALES_AGREEMENT', 'N', 'PRODUCT_AGREEMENT');
INSERT INTO AGREEMENT_TYPE (AGREEMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EMPLOYMENT_AGREEMENT', 'N', '');
INSERT INTO AGREEMENT_TYPE (AGREEMENT_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_AGREEMENT', 'N', '');

-- Agreement Item Type
INSERT INTO AGREEMENT_ITEM_TYPE (AGREEMENT_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('SUBAGREEMENT', 'N', '');
INSERT INTO AGREEMENT_ITEM_TYPE (AGREEMENT_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AGREEMENT_EXHIBIT', 'N', '');
INSERT INTO AGREEMENT_ITEM_TYPE (AGREEMENT_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AGREEMENT_PRICING_PROGRAM', 'N', '');
INSERT INTO AGREEMENT_ITEM_TYPE (AGREEMENT_ITEM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AGREEMENT_SECTION', 'N', '');

-- Term Type
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('FINANCIAL_TERM', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INCENTIVE', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('LEGAL_TERM', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('THRESHOLD', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CLAUSE_FOR_RENEWAL', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('AGREEMENT_TERMINATION', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('INDEMNIFICATION', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('NON_COMPETE', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('EXCLUSIVE_RELATIONSHIP', 'N', '');
INSERT INTO TERM_TYPE (TERM_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('OTHER_TERM', 'N', '');

-- Party Qualification Type
INSERT INTO PARTY_QUAL_TYPE (PARTY_QUAL_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('CERTIFICATION', 'N', '');
INSERT INTO PARTY_QUAL_TYPE (PARTY_QUAL_TYPE_ID, HAS_TABLE, PARENT_TYPE_ID) VALUES ('DEGREE', 'N', '');

COMMIT;

