
-- State/Province Geographic Boundaries
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('AK', 'STATE', 'Alaska', '', 'AZ');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('AL', 'STATE', 'Alabama', '', 'AL');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('AR', 'STATE', 'Akansas', '', 'AR');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('AZ', 'STATE', 'Arizona', '', 'AZ');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('CA', 'STATE', 'California', '', 'CA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('CO', 'STATE', 'Colorado', '', 'CO');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('CT', 'STATE', 'Connecticut', '', 'CT');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('DC', 'STATE', 'Washington DC', '', 'DC');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('DE', 'STATE', 'Delaware', '', 'DE');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('FL', 'STATE', 'Florida', '', 'FL');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('GA', 'STATE', 'Georgia', '', 'GA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('GU', 'STATE', 'Guam', '', 'GU');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('HI', 'STATE', 'Hawaii', '', 'HI');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('IA', 'STATE', 'Iowa', '', 'IA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('ID', 'STATE', 'Idaho', '', 'ID');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('IL', 'STATE', 'Illinois', '', 'IL');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('IN', 'STATE', 'Indiana', '', 'IN');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('KS', 'STATE', 'Kansas', '', 'KS');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('KY', 'STATE', 'Kentucky', '', 'KY');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('LA', 'STATE', 'Louisianna', '', 'LA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MA', 'STATE', 'Massachusetts', '', 'MA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MD', 'STATE', 'Maryland', '', 'MD');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('ME', 'STATE', 'Maine', '', 'ME');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MI', 'STATE', 'Michigan', '', 'MI');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MN', 'STATE', 'Minnesota', '', 'MN');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MO', 'STATE', 'Missourri', '', 'MO');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MS', 'STATE', 'Mississippi', '', 'MS');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('MT', 'STATE', 'Montana', '', 'MT');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NC', 'STATE', 'North Carolina', '', 'NC');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('ND', 'STATE', 'North Dakota', '', 'ND');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NE', 'STATE', 'Nebraska', '', 'NE');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NH', 'STATE', 'New Hampshire', '', 'NH');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NJ', 'STATE', 'New Jersey', '', 'NJ');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NM', 'STATE', 'New Mexico', '', 'NM');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NV', 'STATE', 'Nevada', '', 'NV');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('NY', 'STATE', 'New York', '', 'NY');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('OH', 'STATE', 'Ohio', '', 'OH');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('OK', 'STATE', 'Oklahoma', '', 'OK');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('OR', 'STATE', 'Oregon', '', 'OR');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('PA', 'STATE', 'Pennsylvania', '', 'PA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('PR', 'STATE', 'Puerto Rico', '', 'PR');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('RI', 'STATE', 'Rhode Island', '', 'RI');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('SC', 'STATE', 'South Carolina', '', 'SC');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('SD', 'STATE', 'South Dakota', '', 'SD');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('TN', 'STATE', 'Tennessee', '', 'TN');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('TX', 'STATE', 'Texas', '', 'TX');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('UT', 'STATE', 'Utah', '', 'UT');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('VA', 'STATE', 'Virginia', '', 'VA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('VI', 'STATE', '', '', 'VI');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('VT', 'STATE', 'Vermont', '', 'VT');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('WA', 'STATE', 'Washington', '', 'WA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('WI', 'STATE', 'Wisconson', '', 'WI');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('WV', 'STATE', 'West Virginia', '', 'WV');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('WY', 'STATE', 'Wyoming', '', 'WY');

INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Alberta', 'STATE', 'Alberta', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('British Columbia', 'STATE', 'British Columbia', '', 'AZ');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Manitoba', 'STATE', 'Manitoba', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('New Brunswick', 'STATE', 'New Brunswick', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Newfoundland', 'STATE', 'Newfoundland', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Nova Scotia', 'STATE', 'Nova Scotia', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Northwest Territories', 'STATE', 'Northwest Territories', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Ontario', 'STATE', 'Ontario', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Prince Edward Island', 'STATE', 'Prince Edward Island', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Quebec', 'STATE', 'Quebec', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Sasakatchewan', 'STATE', 'Sasakatchewan', '', '');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('Yukon', 'STATE', 'Yukon', '', '');

-- Country Geographic Boundaries
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('USA', 'COUNTRY', 'United States', '', 'USA');
INSERT INTO GEO (GEO_ID, GEO_TYPE_ID, NAME, GEO_CODE, ABBREVIATION) VALUES ('CAN', 'COUNTRY', 'Canada', '', 'CAN');

COMMIT;


