<table width="170"><tr>
                    <td width="170" height="100%"><table width="170" height="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                        <td width="170" height="10" align="center" valign="top"><img src="/hotelfrontend/images/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="170" align="center" valign="middle" class="unnamed2"><!-- Clock Part 1 - Put Anywhere Before Part 2 -->

<script language="JavaScript">
// Clock Script Generated By Maxx Blade's Clock v2.0
// http://www.maxxblade.co.uk/clock

function tS(){ x=new Date(tN().getUTCFullYear(),tN().getUTCMonth(),tN().getUTCDate(),tN().getUTCHours(),tN().getUTCMinutes(),tN().getUTCSeconds()); x.setTime(x.getTime()+25170000); return x; } 
function tN(){ return new Date(); } 
function lZ(x){ return (x>9)?x:'0'+x; } 
function dE(x){ if(x==1||x==21||x==31){ return 'st'; } if(x==2||x==22){ return 'nd'; } if(x==3||x==23){ return 'rd'; } return 'th'; } 
function dT(){ if(fr==0){ fr=1; document.write('<span id="tP">'+eval(oT)+'</span>'); } document.getElementById('tP').innerHTML=eval(oT); setTimeout('dT()',1000); } 
function y4(x){ return (x<500)?x+1900:x; } 
var dN=new Array('Sun','Mon','Tue','Wed','Thu','Fri','Sat'),mN=new Array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'),fr=0,oT="lZ(tS().getHours())+':'+lZ(tS().getMinutes())+':'+lZ(tS().getSeconds())+'<'+'b'+'r'+'>'+dN[tS().getDay()]+' '+tS().getDate()+dE(tS().getDate())+' '+mN[tS().getMonth()]+' '+y4(tS().getYear())";
</script>

<!-- Clock Part 1 - Ends Here  -->


<!-- Clock Part 2 - This Starts/Displays Your Clock -->

<script language="JavaScript">dT();</script>

<!-- Clock Part 2 - Ends Here --></td>
                      </tr>
                      <tr>
                        <td width="170" height="10" align="center" valign="middle"><img src="/hotelfrontend/images/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="170" height="100%" align="center" valign="middle"><script webstyle3>document.write('<scr'+'ipt src="/hotelfrontend/images/dimpleroundend.js">'+'</scr'+'ipt>');/*img src="DimpleRoundend.gif" moduleid="Default (Project)\DimpleRoundend1_off.xws"*/</script>
                        
                          </td>
                      </tr>
                      <tr>
                        <td width="170" height="10" align="center" valign="top"><img src="/hotelfrontend/images/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="170" align="center" valign="top">
                      </tr>
                      <tr>
                        <td width="170" align="center" valign="top">&nbsp;</td>
                      </tr>
                    </table></td>
</tr></table>