<table width="200"><tr>
                    <td width="200" height="100%"><table width="200" height="100%" border="0" align="center" cellpadding="0" cellspacing="0">
                      <tr>
                        <td width="200" height="10" align="center" valign="top"><img src="/images/frontend/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="200" align="center" valign="middle" class="unnamed2"><!-- Clock Part 1 - Put Anywhere Before Part 2 -->

<script language="JavaScript">
// Clock Script Generated By Maxx Blade's Clock v2.0
// http://www.maxxblade.co.uk/clock

function tS(){ x=new Date(tN().getUTCFullYear(),tN().getUTCMonth(),tN().getUTCDate(),tN().getUTCHours(),tN().getUTCMinutes(),tN().getUTCSeconds()); x.setTime(x.getTime()+25200000); return x; } 
function tN(){ return new Date(); } 
function lZ(x){ return (x>9)?x:'0'+x; } 
function dE(x){ if(x==1||x==21||x==31){ return 'st'; } if(x==2||x==22){ return 'nd'; } if(x==3||x==23){ return 'rd'; } return 'th'; } 
function dT(){ if(fr==0){ fr=1; document.write('<span id="tP">'+eval(oT)+'</span>'); } document.getElementById('tP').innerHTML=eval(oT); setTimeout('dT()',1000); } 
function y4(x){ return (x<500)?x+1900:x; } 
var dN=new Array('Sun','Mon','Tue','Wed','Thu','Fri','Sat'),mN=new Array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'),fr=0,oT="lZ(tS().getHours())+':'+lZ(tS().getMinutes())+':'+lZ(tS().getSeconds())+'<'+'b'+'r'+'>'+dN[tS().getDay()]+' '+tS().getDate()+dE(tS().getDate())+' '+mN[tS().getMonth()]+' '+y4(tS().getYear())";
</script>

<!-- Clock Part 1 - Ends Here  -->


<!-- Clock Part 2 - This Starts/Displays Your Clock -->

<script language="JavaScript">dT();</script>

<!-- Clock Part 2 - Ends Here --></td>
                      </tr>
                      <tr>
                        <td width="200" height="10" align="center" valign="middle"><img src="/images/frontend/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="200" height="100%" align="center" valign="middle"><script webstyle3>document.write('<scr'+'ipt src="/images/frontend/dimpleroundend.js">'+'</scr'+'ipt>');/*img src="DimpleRoundend.gif" moduleid="Default (Project)\DimpleRoundend1_off.xws"*/</script>
                        
                          </td>
                      </tr>
                      <tr>
                        <td width="200" height="10" align="center" valign="top"><img src="/images/frontend/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="200" align="center" valign="top"><table width="200" border="0" align="center" cellpadding="0" cellspacing="0">
                          <tr>
                            <td width="200" height="21" align="center" valign="middle" background="/images/frontend/title_bar.gif"><table width="200" height="21" border="0" align="center" cellpadding="0" cellspacing="0">
                                <tr valign="middle">
                                  <td width="10" height="21" align="center"><img src="/images/frontend/spacer.gif" width="10" height="0" border="0" align="absmiddle"></td>
                                  <td height="21" align="left"><img src="/images/frontend/arrow.gif" width="9" height="9" border="0" align="absmiddle"> <a href="http://www.rydges-chiangmai.com/roomfacilities.shtml" target="_self" class="unnamed1">Room
                                      Rates</a></td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                          <tr>
                            <td width="200" align="center" valign="middle"><table width="200" border="0" align="center" cellpadding="0" cellspacing="0">
                                <tr align="center" valign="middle">
                                  <td width="10" background="/images/frontend/l_bar.gif"><img src="/images/frontend/spacer.gif" width="10" height="0" border="0" align="absmiddle"></td>
                                  <td width="200" align="center" bgcolor="#FFFFFF" class="unnamed5"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" class="unnamed5">
                                    <tr align="left" valign="middle" class="unnamed4">
                                      <td>Room
      Type:</td>
                                      <td>Internet Rate:</td>
                                    </tr>
                                    <tr align="left" valign="middle" class="unnamed5">
                                      <td>Superior</td>
                                      <td>Bt. 2,000</td>
                                    </tr>
                                    <tr align="left" valign="middle" class="unnamed5">
                                      <td>Deluxe</td>
                                      <td>Bt. 2,300</td>
                                    </tr>
                                    <tr align="left" valign="middle" class="unnamed5">
                                      <td>Princess</td>
                                      <td>Bt. 5,000</td>
                                    </tr>
                                    <tr align="left" valign="middle" class="unnamed5">
                                      <td>Ambassador</td>
                                      <td>Bt. 7,000</td>
                                    </tr>
                                    <tr align="left" valign="middle" class="unnamed5">
                                      <td>President</td>
                                      <td>Bt. 15,000</td>
                                    </tr>
                                  </table>
</td>
                                  <td width="12" background="/images/frontend/r_bar.gif"><img src="/images/frontend/spacer.gif" width="12" height="0" border="0" align="absmiddle"></td>
                                </tr>
                                <tr align="center" valign="middle">
                                  <td background="/images/frontend/l_bar.gif">&nbsp;</td>
                                  <td align="center" bgcolor="#FFFFFF"><a href="http://www.rydges-chiangmai.com/roomfacilities.shtml" target="_self" class="unnamed1">More &gt;&gt;&gt;</a></td>
                                  <td background="/images/frontend/r_bar.gif">&nbsp;</td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                          <tr>
                            <td width="200" height="19" align="center" valign="middle" background="/images/frontend/bot_bar.gif"><table width="200" height="19" border="0" align="center" cellpadding="0" cellspacing="0">
                                <tr>
                                  <td width="200" height="19" align="center" valign="middle">&nbsp;</td>
                                </tr>
                              </table>
                            </td>
                          </tr>
                        </table></td>
                      </tr>
                      <tr>
                        <td width="200" height="10" align="center" valign="top"><img src="/images/frontend/spacer.gif" width="0" height="10" border="0" align="absmiddle"></td>
                      </tr>
                      <tr>
                        <td width="200" align="center" valign="top"><table width="200" border="0" align="center" cellpadding="0" cellspacing="0">
                          <tr>
                            <td width="200" height="21" align="center" valign="middle" background="/images/frontend/title_bar.gif"><table width="200" height="21" border="0" align="center" cellpadding="0" cellspacing="0">
                              <tr valign="middle">
                                <td width="10" height="21" align="center"><img src="/images/frontend/spacer.gif" width="10" height="0" border="0" align="absmiddle"></td>
                                <td height="21" align="left"><img src="/images/frontend/arrow.gif" width="9" height="9" border="0" align="absmiddle"> <a href="http://www.rydges-chiangmai.com/golf_special.shtml" target="_self" class="unnamed1">Special
                                  Deals</a></td>
                              </tr>
                            </table></td>
                          </tr>
                          <tr>
                            <td width="200" align="center" valign="middle"><table width="200" border="0" align="center" cellpadding="0" cellspacing="0">
                              <tr align="center" valign="middle">
                                <td width="10" background="/images/frontend/l_bar.gif"><img src="/images/frontend/spacer.gif" width="10" height="0" border="0" align="absmiddle"></td>
                                <td align="left" bgcolor="#FFFFFF" class="unnamed5"><span class="unnamed4">Golf
                                  Package:</span><br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"> 5
                                  days / 4 nights<br>
                                  <img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"> Single
                                  room Bt. 15,000<br>                                  
                                  <img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"> Twin/Double
                                  Bt. 21,500<br>
                                  <br>
                                  </span><span class="unnamed4">Package includes:</span><br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Four
                                  nights in deluxe room<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Free
                                  mini bar consumption<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Daily
                                  buffet breakfast<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> One
                                  free massage <br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Three
                                  days of golf<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span>                                  Free
                                  caddie<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Roundtrip
                                  transfer<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Welcome
                                  drink<br>
                                  <span class="unnamed5"><img src="/images/frontend/bulletb.gif" width="8" height="8" border="0" align="absmiddle"></span> Fruit
                                  basket<br></td>
                                <td width="12" background="/images/frontend/r_bar.gif"><img src="/images/frontend/spacer.gif" width="12" height="0" border="0" align="absmiddle"></td>
                              </tr>
                              <tr align="center" valign="middle">
                                <td background="/images/frontend/l_bar.gif">&nbsp;</td>
                                <td align="center" bgcolor="#FFFFFF"><a href="http://www.rydges-chiangmai.com/golf_special.shtml" target="_self" class="unnamed1">More &gt;&gt;&gt;</a></td>
                                <td background="/images/frontend/r_bar.gif">&nbsp;</td>
                              </tr>
                            </table></td>
                          </tr>
                          <tr>
                            <td width="200" height="19" align="center" valign="middle" background="/images/frontend/bot_bar.gif"><table width="200" height="19" border="0" align="center" cellpadding="0" cellspacing="0">
                              <tr>
                                <td width="200" height="19" align="center" valign="middle">&nbsp;</td>
                              </tr>
                            </table></td>
                          </tr>
                        </table></td>
                      </tr>
                      <tr>
                        <td width="200" align="center" valign="top">&nbsp;</td>
                      </tr>
                    </table></td>
</tr></table>